"""add ondelete cascaded in board_member secondary table

Revision ID: 18459ea7624f
Revises: d3e4d7cb59c9
Create Date: 2026-03-24 22:03:52.090044

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = '18459ea7624f'
down_revision = 'd3e4d7cb59c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_board_member_user_id_user_account'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_board_member_board_id_board'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_board_member_user_id_user_account'), 'user_account', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_board_member_board_id_board'), 'board', ['board_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_board_member_board_id_board'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_board_member_user_id_user_account'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_board_member_board_id_board'), 'board', ['board_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_board_member_user_id_user_account'), 'user_account', ['user_id'], ['id'])

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
